site_name: Economía de trinchera        # Nombre visible del sitio
site_url: https://ariznaf.github.io/ecotrinchera/  # URL pública del sitio (importante para SEO)
use_directory_urls: false                # Usa URLs con .html en vez de directorios
extra_css:
  - styles/extra.css                    # CSS adicional para personalizar estilos

extra:
  social:                               # Iconos sociales en la cabecera o footer
    - icon: material/home               # Icono de "home" de Material Icons
      link: /                           # Enlace al inicio del sitio
extra_javascript:
  - js/giscus.js
markdown_extensions:
  - attr_list                           # Permite atributos en Markdown (clases, estilos, etc.)

theme:
  name: material                        # Usa el tema Material for MkDocs
  custom_dir: overrides                 # Carpeta con plantillas personalizadas (como main.html)

  # Paletas de colores (modo oscuro y claro)
  palette:
    - scheme: slate                     # Modo oscuro
      primary: indigo                   # Color primario
      accent: indigo                    # Color de acento
      toggle:
        icon: material/weather-sunny    # Icono del botón para cambiar a modo claro
        name: Cambiar a modo claro      # Texto accesible del botón
    - scheme: default                   # Modo claro
      primary: indigo                   # Color primario
      accent: indigo                    # Color de acento
      toggle:
        icon: material/weather-night    # Icono del botón para cambiar a modo oscuro
        name: Cambiar a modo oscuro     # Texto accesible del botón

  features:
    - navigation.tabs                   # Muestra pestañas en la navegación superior
    - navigation.top                    # Botón para volver arriba
    - navigation.instant                # Navegación instantánea sin recargar página
    - navigation.path                   # Muestra la ruta (breadcrumb) de la página

nav:                                    # Estructura del menú de navegación
  - Inicio: index.md
  - Ideas:
      - ideas/index.md
      - Contabilidad 3.0:
          - ideas/contabilidad3/index.md
          - ideas/contabilidad3/uuid.md
          - ideas/contabilidad3/agentes.md
          - ideas/contabilidad3/registradores.md
          - ideas/contabilidad3/cuentas_traspasos.md
          - ideas/contabilidad3/operaciones_internas.md
          - ideas/contabilidad3/operaciones_externas.md
          - ideas/contabilidad3/valores_cotizables.md
          - ideas/contabilidad3/ejemplos.md
          - ideas/contabilidad3/seguridad.md
          - ideas/contabilidad3/marco_legal_y_transicion.md
          - ideas/contabilidad3/migracion_voluntaria.md
          - ideas/contabilidad3/integracion_sistemas_tradicionales.md
          - ideas/contabilidad3/conclusion.md
  - Programas:
      - programas/index.md
  - Inversión:
      - inversion/index.md